general:
  project_name: coco_person_detection
  model_type: st_ssd_mobilenet_v1
  model_path:
  logs_dir: logs
  saved_models_dir: saved_models
  gpu_memory_limit: 16
  global_seed: 127
operation_mode: chain_tqeb
dataset:
  name: person_dataset
  class_names: [person]
  training_path: DATASETS/person_train_set
  validation_path: DATASETS/person_val_set
  test_path:
  quantization_path:
  quantization_split: 0.3
preprocessing:
  rescaling:  {scale : 127.5, offset : -1}
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb
data_augmentation:
  rotation: 30
  shearing: 15
  translation: 0.1
  vertical_flip: 0.5
  horizontal_flip: 0.2
  gaussian_blur: 3.0
  linear_contrast: [0.75, 1.5]
training:
  model:
    alpha: 0.25
    input_shape: (256, 256, 3)
    pretrained_weights: imagenet
  dropout: null
  batch_size: 64
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      patience: 20
    EarlyStopping:
      monitor: val_loss
      patience: 40
postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.4
  plot_metrics: true
  max_detection_boxes: 10
quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
benchmarking:
  board: STM32H747I-DISCO
tools:
  stedgeai:
    version: 9.1.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe
deployment:
  c_project_path: ../../stm32ai_application_code/object_detection/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO
mlflow:
  uri: ./experiments_outputs/mlruns
hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}