general:
  project_name: tf_food101
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: true
  global_seed: 127
  gpu_memory_limit: 16
operation_mode: chain_tqe
dataset:
  name: food101
  class_names:
  - apple_pie
  - baby_back_ribs
  - baklava
  - beef_carpaccio
  - beef_tartare
  - beet_salad
  - beignets
  - bibimbap
  - bread_pudding
  - breakfast_burrito
  - bruschetta
  - caesar_salad
  - cannoli
  - caprese_salad
  - carrot_cake
  - ceviche
  - cheesecake
  - cheese_plate
  - chicken_curry
  - chicken_quesadilla
  - chicken_wings
  - chocolate_cake
  - chocolate_mousse
  - churros
  - clam_chowder
  - club_sandwich
  - crab_cakes
  - creme_brulee
  - croque_madame
  - cup_cakes
  - deviled_eggs
  - donuts
  - dumplings
  - edamame
  - eggs_benedict
  - escargots
  - falafel
  - filet_mignon
  - fish_and_chips
  - foie_gras
  - french_fries
  - french_onion_soup
  - french_toast
  - fried_calamari
  - fried_rice
  - frozen_yogurt
  - garlic_bread
  - gnocchi
  - greek_salad
  - grilled_cheese_sandwich
  - grilled_salmon
  - guacamole
  - gyoza
  - hamburger
  - hot_and_sour_soup
  - hot_dog
  - huevos_rancheros
  - hummus
  - ice_cream
  - lasagna
  - lobster_bisque
  - lobster_roll_sandwich
  - macaroni_and_cheese
  - macarons
  - miso_soup
  - mussels
  - nachos
  - omelette
  - onion_rings
  - oysters
  - pad_thai
  - paella
  - pancakes
  - panna_cotta
  - peking_duck
  - pho
  - pizza
  - pork_chop
  - poutine
  - prime_rib
  - pulled_pork_sandwich
  - ramen
  - ravioli
  - red_velvet_cake
  - risotto
  - samosa
  - sashimi
  - scallops
  - seaweed_salad
  - shrimp_and_grits
  - spaghetti_bolognese
  - spaghetti_carbonara
  - spring_rolls
  - steak
  - strawberry_shortcake
  - sushi
  - tacos
  - takoyaki
  - tiramisu
  - tuna_tartare
  - waffles
  training_path: ../datasets/food-101/images
  validation_path: null
  validation_split: 0.2
  test_path: null
  quantization_path: null
  quantization_split: null
  check_image_files: false
  seed: 127
preprocessing:
  rescaling:
    scale: 1/255.0
    offset: 0.0
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb
data_augmentation:
  random_hue:
    delta: 0.04
    change_rate: 1.0
  random_contrast:
    factor: 0.6
    change_rate: 1.0
  random_brightness:
    factor: 0.05
    change_rate: 1.0
  random_rectangle_erasing:
    nrec: (0, 10)
    area: (0.0, 0.1)
    wh_ratio: (0.25, 4.0)
    fill_method: mosaic
    mode: batch
    change_rate: 0.05
  random_flip:
    mode: horizontal
    change_rate: 1.0
  random_translation:
    width_factor: 0.2
    height_factor: 0.2
    fill_mode: reflect
    interpolation: nearest
    change_rate: 1.0
  random_rotation:
    factor: 0.125
    fill_mode: reflect
    interpolation: nearest
    change_rate: 1.0
  random_zoom:
    width_factor: 0.2
    height_factor: 0.2
    fill_mode: reflect
    interpolation: nearest
    change_rate: 1.0
  random_shear:
    factor: 0.15
    fill_mode: wrap
    interpolation: nearest
    change_rate: 1.0
training:
  model:
    name: st_efficientnet_lc
    version: v1
    input_shape: (128, 128, 3)
  resume_training_from: null
  dropout: 0.25
  batch_size: 128
  epochs: 500
  optimizer:
    Adam:
      learning_rate: 0.002
  callbacks:
    ReduceLROnPlateau:
      monitor: val_accuracy
      mode: max
      factor: 0.5
      patience: 30
      min_lr: 1.0e-05
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: true
      patience: 100
quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
prediction: null
tools:
  stedgeai:
    version: 9.1.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe
benchmarking:
  board: STM32H747I-DISCO
deployment:
  c_project_path: ../../stm32ai_application_code/image_classification/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO
    input: CAMERA_INTERFACE_DCMI
    output: DISPLAY_INTERFACE_USB
mlflow:
  uri: ./experiments_outputs/mlruns
hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}

