general:
  project_name: coco
  model_type: st_yolo_lc_v1
  model_path: 
  logs_dir: logs
  saved_models_dir: saved_models
  gpu_memory_limit: 5
  global_seed: 127
operation_mode: chain_tqe
dataset:
  name: coco_person
  class_names:
  - person
  training_path: ../datasets/coco2017_person/train
  validation_path: ../datasets/coco2017_person/val
  test_path: ../datasets/coco2017_person/val
  quantization_path: null
  quantization_split: 0.01
preprocessing:
  rescaling:
    scale: 1/255
    offset: 0
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb
data_augmentation:
  rotation: 5
  shearing: null
  translation: 0.1
  vertical_flip: null
  horizontal_flip: 1.0
  gaussian_blur: 3.0
  linear_contrast:
  - 0.75
  - 1.5
training:
  model:
    alpha: 0.25
    input_shape: (256,256,3)
    pretrained_weights: null
  dropout: null
  batch_size: 64
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.01
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      patience: 50
      verbose: 1
      min_delta: 0.05
      min_lr: 1.0e-06
    EarlyStopping:
      monitor: val_loss
      patience: 80
      verbose: 1
      min_delta: 0.05
postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.4
  plot_metrics: true
  max_detection_boxes: 1280
  yolo_anchors:
  - 0.0252
  - 0.06
  - 0.0772
  - 0.1829
  - 0.1696
  - 0.4167
  - 0.3339
  - 0.6559
  - 0.7226
  - 0.7348
quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
benchmarking:
  board: STM32H747I-DISCO
tools:
  stedgeai:
    version: 9.1.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe
deployment:
  c_project_path: ../../stm32ai_application_code/object_detection/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO
mlflow:
  uri: ./experiments_outputs/mlruns
